
name: DevSecOps CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  build:
    name: Build OWASP Juice Shop
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker image
        run: |
          docker pull bkimminich/juice-shop

  security:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # CodeQL for SAST
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript-typescript'
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Snyk for SCA
      - name: Set up Node.js for Snyk
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Start Juice Shop Docker Container
      - name: Start Juice Shop Docker Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

      # ZAP Scan for DAST
      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'

      # Upload ZAP scan results as artifact
      - name: Upload ZAP results as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: zap-results
          path: /home/runner/work/DevSecOps-CI-CD-Pipeline/DevSecOps-CI-CD-Pipeline/*.html
